---
# Installation des paquets
- name: Installation des paquets pour l'installation du serveur mail
  apt: name={{ item }} state=latest
  with_items:
    - procmail
    - courier-imap

# Suppression du repertoire de sauvegarde
- name: Suppression de /etc/
  file: path='/var/sauvegarde/etc/' state=absent

- name: Suppression de /var/
  file: path='/var/sauvegarde/var/' state=absent

# Sauvegardes des repertoires dans /etc/ et /var/
- name: Sauvegarde de /etc/
  command: mv {{ item }} /var/sauvegarde/etc/
  with_items:
        - /etc/courier/
        - /etc/aliases
        - /etc/aliases.db
        - /etc/procmailrc
        - /etc/procmailrc.old

- name: Sauvegarde de /var/
  command: mv {{ item }} /var/sauvegarde/var/
  with_items:
        - /var/mail/
        - /var/vmail/

# Déplacer les contenues des dossiers GITHUB dans le bon repertoire
- name: Déplacer le contenu (les dossiers) de /var/github/etc/ vers /etc/
  command: mv /var/github/etc/{{ item }} /etc/
  with_items:
        - /var/github/etc/courier/
        - /var/github/etc/aliases
        - /var/github/etc/aliases.db
        - /var/github/etc/procmailrc
        - /var/github/etc/procmailrc.old

- name: Déplacer le contenu (les dossiers) de /var/github/var/ vers /var/
  command: mv /var/github/var/{{ item }} /var/
  with_items:
        - /var/github/var/mail/
        - /var/github/var/vmail/
...