---
# Installation des paquets
- name: Installation des paquets pour l'installation du serveur mail
  apt: name={{ item }} state=latest
  with_items:
    - procmail
    - courier-imap
    - exim4
    - sa-exim

# Suppression du repertoire de sauvegarde
- name: Suppression de /etc/
  local_action: stat path=/var/sauvegarde/etc/
  register: dossier

- file: path='/var/sauvegarde/etc/' state=absent
  when: dossier.stat.exists

- name: Suppression de /var/
  local_action: stat path=/var/sauvegarde/var/
  register: dossier

- file: path='/var/sauvegarde/etc/' state=absent
  when: dossier.stat.exists

# Sauvegardes des repertoires dans /etc/ et /var/
- name: Sauvegarde de /etc/
  local_action: stat path={{ item }}
  set_fact: some_variable={{ some_variable | int + 1 }}
  register: dossier_some_variable
  with_items:
        - /etc/courier/
        - /etc/exim4/
        - /etc/aliases
        - /etc/aliases.db

- command: mv {{ item }} /var/sauvegarde/etc/
  when: dossier_some_variable.stat.exists
  with_items:
        - /etc/courier/
        - /etc/exim4/
        - /etc/aliases
        - /etc/aliases.db

- name: Sauvegarde de /var/
  command: mv {{ item }} /var/sauvegarde/var/
  with_items:
        - /var/mail/
        - /var/vmail/

# Déplacer les contenues des dossiers GITHUB dans le bon repertoire
- name: Déplacer le contenu (les dossiers) de /var/github/etc/ vers /etc/
  command: mv {{ item }} /etc/
  with_items:
        - /var/github/etc/courier/
        - /var/github/etc/aliases
        - /var/github/etc/aliases.db
        - /var/github/etc/procmailrc
        - /var/github/etc/procmailrc.old

- name: Déplacer le contenu (les dossiers) de /var/github/var/ vers /var/
  command: mv {{ item }} /var/
  with_items:
        - /var/github/var/mail/
        - /var/github/var/vmail/
...