---
# Déplacer les contenues des dossiers GITHUB dans le bon repertoire
- name: Déplacer le contenu de /var/github/etc/ vers /etc/
  become: true
  become_method: su
  command: mv /var/github/etc/ /etc/

- name: Déplacer le contenu de /var/github/var/ vers /var/
  become: true
  become_method: su
  command: mv /var/github/var/ /var/

# Suppression des repertoires vides
- name: Suppression de /etc/github/etc/
  file:
    path: '/var/github/etc/'
    state: absent

- name: Suppression de /var/github/var/
  file:
    path: '/var/github/var/'
    state: absent

- name: Suppression de /var/github/
  file:
    path: '/var/github/'
    state: absent
...